spring:
  application:
    name: product-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://config-server:8888/}"
  cloud:
    config:
      # Bật fail-fast và retry để đảm bảo service chờ Config Server sẵn sàng
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        max-attempts: 6
      username: nexus_admin
      password: ${CONFIG_SERVER_PASSWORD}
  
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes
      cache-null-values: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
