input {
  tcp {
    port => 50000
    codec => json_lines
  }
}

filter {
  if ![service_name] {
    mutate { add_field => { "service_name" => "unknown" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "nexus-logs-%{service_name}-%{+YYYY.MM.dd}"
  }
  if [LOGSTASH_DEBUG] == "true" {
    stdout { codec => rubydebug }
  }
}
