server:
  port: 8082 # Đổi 8081 → 8082 vì Keycloak container đang chiếm port 8081 (docker-compose: 8081:8080)

spring:
  # CẤU HÌNH DATABASE (PostgreSQL)
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/nexus_db} # Trỏ tới Data container được dựng bởi docker-compose
    username: ${POSTGRES_USER:nexus_user}
    password: ${POSTGRES_PASSWORD:nexus_password}
  jpa:
    show-sql: true # Log script SQL SQL/Query ra màn hình để dễ bắt bug lúc code.
    hibernate:
      ddl-auto: validate # Default fallback

  # CẤU HÌNH KAFKA MESSAGE BROKER (Saga Pattern)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092} # Trỏ tay tới địa chỉ broker Kafka.
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "order-service-group" # Nhóm người nghe của Order Service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.nexus.orderservice"

  # CẤU HÌNH SPRING CLOUD STREAM (Reliability - Phase 3)
  cloud:
    stream:
      kafka:
        bindings:
          # Cấu hình DLQ cho Consumer nhận phản hồi từ Kho
          process-inventory-response-in-0:
            consumer:
              enable-dlq: true # BẬT CHẾ ĐỘ CÁCH LY TIN NHẮN LỖI (DLQ)
              dlq-name: inventory-events-topic.dlq # Tên Topic chứa tin nhắn chết
              dlq-partitions: 1
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

      # Chiến lược Retry (Cố gắng thử lại trước khi đẩy vào DLQ)
      bindings:
        process-inventory-response-in-0:
          consumer:
            max-attempts: 3 # Thử lại tối đa 3 lần
            back-off-initial-interval: 1000 # Lần 1: 1 giây
            back-off-multiplier: 2.0 # Lũy thừa thời gian (Lần 2: 2s, Lần 3: 4s)
            back-off-max-interval: 10000 # Không quá 10 giây

# CẤU HÌNH SERVICE DISCOVERY (EUREKA)
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  tracing:
    sampling:
      probability: ${SAMPLING_PROBABILITY:0.1}
  zipkin:
    tracing:
      endpoint: http://nexus-zipkin:9411/api/v2/spans

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
