server:
  port: 8083

spring:
  # CẦU HÌNH DATABASE (MongoDB)
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/nexus_db}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# CẤU HÌNH SERVICE DISCOVERY (EUREKA)
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: ${SAMPLING_PROBABILITY:0.1} # request sẽ được trace (configurable, default 10%)
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
