server:
    port: 8888

spring:
    application:
        name: config-server
    profiles:
        active: native # Dùng thư mục cục bộ (Native) để quản lý cấu hình, phù hợp chạy local
    cloud:
        config:
            server:
                native:
                    # Trỏ thẳng vào thư mục source file ở máy tính (thay vì classpath) để hỗ trợ cập nhật thay đổi file ngay lập tức (Hot Reloading) mà không cần build lại.
                    search-locations: "classpath:/config-repo/,file:./config-server/src/main/resources/config-repo/,file:./src/main/resources/config-repo/"
