server:
    port: 8888

spring:
    application:
        name: config-server
    profiles:
        active: native # Dùng thư mục cục bộ (Native) để quản lý cấu hình, phù hợp chạy local
    cloud:
        config:
            server:
                native:
                    # Trỏ thẳng vào thư mục source file ở máy tính (thay vì classpath) để hỗ trợ cập nhật thay đổi file ngay lập tức (Hot Reloading) mà không cần build lại.
                    search-locations: file://${user.dir}/config-server/src/main/resources/config-repo

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
