server:
    port: 8888

spring:
    application:
        name: config-server
    profiles:
        active: native

    # BẢO MẬT CONFIG SERVER (Phase 3)
    security:
        user:
            name: nexus_admin
            password: ${CONFIG_SERVER_PASSWORD}

    # CẤU HÌNH NATIVE (áp dụng toàn cục)
    cloud:
        config:
            server:
                native:
                    search-locations: "classpath:/config-repo/,file:./config-server/src/main/resources/config-repo/,file:./src/main/resources/config-repo/"

# KEY MÃ HÓA (Dành cho JCE) - Phải được giữ bí mật tuyệt đối trong thực tế
encrypt:
    key: ${CONFIG_SERVER_ENCRYPT_KEY}

---
spring:
    config:
        activate:
            on-profile: dev
    security:
        user:
            password: ${CONFIG_SERVER_PASSWORD:dev_password}
